# Generated by Django 3.0.7 on 2020-07-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dat_eof_birth',
            new_name='date_of_birth',
        ),
    ]
